### ISSUE TITLE
module types are getting mixed together

### ISSUE THREAD

**Issue by miramallows** [piesocket/piesocket-js#1]
this library will not work at all if you acutally test it, without me modifying it myself.
i simply have this snippet of code:
```
const PieSocket = require('piesocket-js')
module.exports = (config) => {
    const piesocket = new PieSocket({
        ...config.piesocket
    })

    const channel = piesocket.subscribe(1)

    channel.on('message', msg => {
        console.log(msg)
    })

}```

which results in
```import Channel from './Channel';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

linked to the piesocket.js file.

**Comment by sudoanand** [comment]
Thanks for reporting this issue, piesocket-js is in beta, and a lot of work is going on which you can see in the next releases.

Can you please mention your environment details?

**Comment by sudoanand** [comment]
Fixed, Upgrading to the latest version should do the trick! Please use ES6 where possible.
