### ISSUE TITLE
How can i subscribe message from client side

### ISSUE THREAD

**Issue by jerrywu001** [piesocket/piesocket-js#17]
How can I subscribe to messages from the client side `channel.publish`? @sudoanand 

Can the server side (like nodejs)   `subscribe` from the client?

**Comment by sudoanand** [comment]
Hello, 

To subscribe. `use .subscribe`

This package is not intended to be used on the server-side. However, you can subscribe to channels on the server-side using a NodeJS WebSocket client, please: [WebSocket Server API](https://www.piesocket.com/docs/3.0/websocket-api)
