### ISSUE TITLE
piesocket.com registration doesn't work

### ISSUE THREAD

**Issue by martinpesava** [piesocket/piesocket-js#3]
Hello, I'm trying to contact you but no way works ... the registration form https://www.piesocket.com/register?plan=free always shows me an error 500 page after submitting. Also the contact form doesn't work ...

**Comment by Guardian1983** [comment]
I have the same problem... Any ETA on when it will be resolved?

**Comment by martinpesava** [comment]
And also it seems, that the info emails with daily summary doesn't come any more ... :-(

**Comment by sudoanand** [comment]
This was resolved! We are checking the daily summary email issues, will be fixed today.
